name: christmas_tree_3d
description: "Flutter 3D Christmas tree demo using flutter_gl and three_dart"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.9.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_gl: ^0.0.21
  three_dart: ^0.0.16
  three_dart_jsm: ^0.0.10  # 可选（建议加）
  vector_math: ^2.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

